WIFI_SSID = "YOUR_WIFI_SSID"
WIFI_PASSWORD = "YOUR_WIFI_PASSWORD"
FAVORIOT_DEVICE_ACCESS_TOKEN = "YOUR_FAVORIOT_DEVICE_ACCESS_TOKEN"
FAVORIOT_DEVICE_DEVELOPER_ID = "YOUR_FAVORIOT_DEVICE_DEVELOPER_ID"
FAVORIOT_MQTT_BROKER_HOST = "mqtt.favoriot.com"
FAVORIOT_MQTT_BROKER_PORT = 1883
FAVORIOT_MQTT_BROKER_SECURE_PORT = 8883
FAVORIOT_HTTPS_API = "https://apiv2.favoriot.com/v2/streams"
FAVORIOT_HTTPS_METHOD = "POST"